controller_list:
  - name: fake_robutler_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_robutler_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper
initial:  # Define initial robot poses per group
  - group: robutler_arm
    pose: home
  - group: robutler_hand
    pose: open